apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - findsources.co.uk
      secretName: findsources-kubernetes-tls
  rules:
    - host: findsources.co.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
---
# Redirect www.findsources.co.uk to findsources.co.uk
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress-www-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/permanent-redirect: https://findsources.co.uk
spec:
  tls:
    - hosts:
      - www.findsources.co.uk
      secretName: www-findsources-kubernetes-tls
  rules:
    - host: www.findsources.co.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
---
# Redirect vrespiges.gr to findsources.co.uk
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress-gr-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/permanent-redirect: https://findsources.co.uk
spec:
  tls:
    - hosts:
      - vrespiges.gr
      secretName: vrespiges-kubernetes-tls
  rules:
    - host: vrespiges.gr
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
---
# Redirect www.vrespiges.gr to findsources.co.uk
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress-gr-www-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/permanent-redirect: https://findsources.co.uk
spec:
  tls:
    - hosts:
      - www.vrespiges.gr
      secretName: www-vrespiges-kubernetes-tls
  rules:
    - host: www.vrespiges.gr
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: producer-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
      - findsources.co.uk
      secretName: findsources-kubernetes-tls
  rules:
    - host: findsources.co.uk
      http:
        paths:
          - path: /api/producer/(.*)
            backend:
              serviceName: producer
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: consumer-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
      - findsources.co.uk
      secretName: findsources-kubernetes-tls
  rules:
    - host: findsources.co.uk
      http:
        paths:
          - path: /api/consumer/(.*)
            backend:
              serviceName: consumer
              servicePort: 80
