apiVersion: apps/v1
kind: Deployment
metadata:
  name: monstache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstache
  template:
    metadata:
      labels:
        app: monstache
    spec:
      containers:
      - name: monstache
        image: findsources/monstache:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./build/linux-amd64/monstache -f config.toml"]
        ports:
        - containerPort: 8080
        env:
        - name: MONSTACHE_CHANGE_STREAM_NS
          valueFrom:
            secretKeyRef:
              name: monstache-secrets
              key: monstache_change_stream_ns
        - name: MONSTACHE_DIRECT_READ_NS
          valueFrom:
            secretKeyRef:
              name: monstache-secrets
              key: monstache_direct_read_ns
        - name: MONSTACHE_MONGO_URL
          valueFrom:
            secretKeyRef:
              name: monstache-secrets
              key: monstache_mongo_url
        - name: MONSTACHE_ES_URLS
          valueFrom:
            secretKeyRef:
              name: monstache-secrets
              key: monstache_es_urls
