apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: producer
        image: findsources/producer:latest
        command: ["/bin/sh"]
        args: ["-c", "pipenv run uvicorn producer.main:app --host 0.0.0.0"]
        ports:
        - containerPort: 8000
        env:
        - name: APP_NAME
          value: 'producer'
        - name: DATABASE_HOST
          value: 'replica-set-mongodb'
        - name: DATABASE_PORT
          value: '27017'
        - name: DATABASE_TYPE
          value: 'mongodb'
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: db_username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: db_password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: db_name
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: google_client_id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: google_client_secret
        - name: GOOGLE_DISCOVERY_URL
          value: 'https://accounts.google.com/.well-known/openid-configuration'
        - name: GOOGLE_REDIRECT_URL
          value: 'https://findsources.co.uk/api/producer/google-login-callback/'
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: azure_tenant_id
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: azure_client_id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: azure_client_secret
        - name: AZURE_DISCOVERY_URL
          value: 'https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration'
        - name: AZURE_REDIRECT_URL
          value: 'https://findsources.co.uk/api/producer/azure-login-callback/'
        - name: FRONTEND_URL
          value: 'https://findsources.co.uk/'
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: jwt_secret_key
        - name: ALGORITHM
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: algorithm
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: '720'
        - name: AUTH_TOKEN_EXPIRE_MINUTES
          value: '3'
