import os


APP_NAME = os.getenv("APP_NAME")

ELASTICSEARCH_HOST = os.getenv("ELASTICSEARCH_HOST")
ELASTICSEARCH_INDEX = os.getenv("ELASTICSEARCH_INDEX")
ELASTICSEARCH_MSEARCH_ENDPOINT = os.getenv("ELASTICSEARCH_MSEARCH_ENDPOINT")

