name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }} 
      run: |
        #echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
        
        echo "Building images"
        #docker build -t findsources/frontend:latest --file react/apps/frontend/Dockerfile .
        #docker build -t findsources/producer:latest --file python/apps/producer/Dockerfile .
        #docker build -t findsources/consumer:latest --file python/apps/consumer/Dockerfile .
        #docker build -t findsources/monstache:latest --file monstache/Dockerfile .
        
        #echo "Pushing images"
        #docker push findsources/frontend
        #docker push findsources/producer
        #docker push findsources/consumer
        #docker push findsources/monstache

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITAL_OCEAN_CLUSTER_ID }}

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl delete pod -l app=consumer

    - name: Remove DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig remove ${{ secrets.DIGITAL_OCEAN_CLUSTER_ID }}
