name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
    - 'python/apps/producer/**'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }} 
      run: |
        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
        
        echo "Building image"
        docker build -t findsources/producer:latest --file python/apps/producer/Dockerfile .
        
        echo "Pushing image"
        docker push findsources/producer

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITAL_OCEAN_CLUSTER_ID }}

    - name: Deploy to DigitalOcean Kubernetes
      run: |
        echo "Restarting pods"
        kubectl delete pod -l app=producer

    - name: Remove DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig remove ${{ secrets.DIGITAL_OCEAN_CLUSTER_ID }}
