name: Snapshots CI

on:
  schedule:
  - cron: "*/2 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITAL_OCEAN_CLUSTER_ID }}

    - name: Deploy to DigitalOcean Kubernetes
      run: |
        echo "Backup snapshot"
        kubectl delete mongo-primary-snapshot
        kubectl create -f deployments/backup-mongo.yaml

    - name: Remove DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig remove ${{ secrets.DIGITAL_OCEAN_CLUSTER_ID }}
